using System.Linq.Expressions;
using LinqToTTreeInterfacesLib;
using LINQToTTreeLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
using LINQToTTreeLib.Variables;
using ROOTNET;
using LINQToTTreeLib.Statements;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.TypeHandlers.ROOT
{
    public partial class TypeHanlderROOTTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException653()
{
    Expression expression;
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew(s0, (NewExpression)null, 
                                 out iValue, (GeneratedCode)null, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException88()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, 0);
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException792()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, 0);
    string[] ss = new string[1];
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException923()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, 1);
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException422()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, 0);
    string[] ss = new string[1];
    ss[0] = "";
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException787()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    string[] ss = new string[1];
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, ss);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException521()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, 0);
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException410()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      VarInteger varInteger;
      NTObject nTObject;
      GeneratedCode generatedCode;
      Expression expression;
      varInteger = VarIntegerFactory.Create(false, int.MaxValue);
      nTObject = NTObjectFactory.Create();
      disposables.Add((IDisposable)nTObject);
      NTObject[] nTObjects = new NTObject[1];
      nTObjects[0] = nTObject;
      generatedCode =
        GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                    (string[])null, nTObjects, (string[])null);
      TypeHandlerROOT s0 = new TypeHandlerROOT();
      IValue iValue = (IValue)null;
      expression = this.ProcessNew
                       (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException578()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger, iStatements, 
                                                (string[])null, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException445()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      VarInteger varInteger;
      NTObject nTObject;
      GeneratedCode generatedCode;
      Expression expression;
      varInteger = VarIntegerFactory.Create(false, int.MaxValue);
      nTObject = NTObjectFactory.Create();
      disposables.Add((IDisposable)nTObject);
      NTObject[] nTObjects = new NTObject[2];
      nTObjects[0] = nTObject;
      nTObjects[1] = nTObject;
      generatedCode =
        GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                    (string[])null, nTObjects, (string[])null);
      TypeHandlerROOT s0 = new TypeHandlerROOT();
      IValue iValue = (IValue)null;
      expression = this.ProcessNew
                       (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(TypeHanlderROOTTest))]
[ExpectedException(typeof(ArgumentException))]
public void ProcessNewThrowsArgumentException603()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementIncrementInteger statementIncrementInteger1;
    StatementInlineBlock statementInlineBlock;
    GeneratedCode generatedCode;
    Expression expression;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementIncrementInteger1 = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[3];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iStatements[1] = (IStatement)statementIncrementInteger1;
    iStatements[2] = (IStatement)statementInlineBlock;
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger, iStatements, 
                                                (string[])null, (NTObject[])null, (string[])null);
    TypeHandlerROOT s0 = new TypeHandlerROOT();
    IValue iValue = (IValue)null;
    expression = this.ProcessNew
                     (s0, (NewExpression)null, out iValue, generatedCode, (CodeContext)null);
}
    }
}
