using LinqToTTreeInterfacesLib;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using LINQToTTreeLib.Variables;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Statements
{
    public partial class StatementInlineBlockTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet216()
{
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet723()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet72301()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet63901()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IVariable[] iVariables = new IVariable[1];
    iVariables[0] = (IVariable)varInteger;
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IVariable)varInteger, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       (IStatement[])null, iVariables);
    IStatement[] iStatements = new IStatement[2];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iStatements[1] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet639()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IVariable)varInteger, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       (IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[2];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iStatements[1] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet63904()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    VarInteger varInteger1;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    varInteger1 = VarIntegerFactory.Create(false, 643);
    IVariable[] iVariables = new IVariable[2];
    iVariables[0] = (IVariable)varInteger1;
    iVariables[1] = (IVariable)varInteger;
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IVariable)varInteger1, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       (IStatement[])null, iVariables);
    IStatement[] iStatements = new IStatement[2];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iStatements[1] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(((StatementInlineBlockBase)statementInlineBlock).Statements);
    Assert.IsTrue(object.ReferenceEquals
                      (((StatementInlineBlockBase)statementInlineBlock).Statements, 
                       (object)iEnumerable));
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementInlineBlock).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementInlineBlock).Parent);
}
    }
}
