using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
using LINQToTTreeLib.Variables;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Tests
{
    public partial class StatementAssignTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void StatementAssignConstructorTestThrowsArgumentNullException517()
{
    StatementAssign statementAssign;
    statementAssign =
      this.StatementAssignConstructorTest((IVariable)null, (IValue)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void StatementAssignConstructorTestThrowsArgumentNullException593()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      this.StatementAssignConstructorTest((IVariable)varInteger, (IValue)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void StatementAssignConstructorTest472()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      this.StatementAssignConstructorTest((IVariable)varInteger, (IValue)varInteger);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
    Assert.IsTrue(object.ReferenceEquals
                      (statementAssign.Expression, statementAssign.ResultVariable));
    Assert.IsNull(statementAssign.Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void StatementAssignConstructorTestThrowsArgumentNullException170()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementAssign =
      this.StatementAssignConstructorTest((IVariable)varInteger, (IValue)null);
}
    }
}
