// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using LINQToTTreeLib.Statements;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace LINQToTTreeLib.Tests.Statements
{
    public partial class StatementLoopOverGroupItemsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(StatementLoopOverGroupItemsTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void TestTryCombineThrowsArgumentNullException302()
        {
            StatementInlineBlockTest.dummyVarName dummyVarName;
            StatementLoopOverGroupItems statementLoopOverGroupItems;
            dummyVarName =
              new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
            dummyVarName.InitialValue = (IValue)null;
            dummyVarName.Declare = false;
            dummyVarName.RawValue = (string)null;
            statementLoopOverGroupItems = StatementLoopOverGroupItemsFactory.Create
                                              ((IValue)dummyVarName, (IStatement)null);
            StatementLoopOverGroupItemsTest.TestTryCombine
                (statementLoopOverGroupItems, (IStatement)null);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(StatementLoopOverGroupItemsTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void TestTryCombine577()
        {
            StatementInlineBlockTest.dummyVarName dummyVarName;
            StatementLoopOverGroupItems statementLoopOverGroupItems;
            StatementLoopOverGroupItems statementLoopOverGroupItems1;
            dummyVarName =
              new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
            dummyVarName.InitialValue = (IValue)null;
            dummyVarName.Declare = false;
            dummyVarName.RawValue = (string)null;
            statementLoopOverGroupItems = StatementLoopOverGroupItemsFactory.Create
                                              ((IValue)dummyVarName, (IStatement)null);
            statementLoopOverGroupItems1 =
              StatementLoopOverGroupItemsFactory.Create((IValue)null, (IStatement)null);
            StatementLoopOverGroupItemsTest.TestTryCombine
                (statementLoopOverGroupItems1, (IStatement)statementLoopOverGroupItems);
            Assert.IsNotNull((object)statementLoopOverGroupItems1);
            Assert.IsNotNull(statementLoopOverGroupItems1.Counter);
            Assert.IsNotNull
                (((StatementInlineBlockBase)statementLoopOverGroupItems1).Statements);
            Assert.IsNotNull
                (((StatementInlineBlockBase)statementLoopOverGroupItems1).DeclaredVariables);
            Assert.IsNull(((StatementInlineBlockBase)statementLoopOverGroupItems1).Parent);
        }
    }
}
