using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
using LINQToTTreeLib.Variables;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Statements
{
    public partial class StatementInlineBlockTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestAddSingleStatementThrowsArgumentNullException532()
{
    this.TestAddSingleStatement((IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement818()
{
    StatementInlineBlock statementInlineBlock;
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement622()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    this.TestAddSingleStatement((IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement62201()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    this.TestAddSingleStatement((IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81804()
{
    StatementInlineBlock statementInlineBlock;
    StatementInlineBlock statementInlineBlock1;
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    IVariable[] iVariables = new IVariable[1];
    iStatements[0] = (IStatement)statementInlineBlock;
    statementInlineBlock1 =
      StatementInlineBlockFactory.Create(iStatements, iVariables);
    this.TestAddSingleStatement((IStatement)statementInlineBlock1);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81802()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81803()
{
    VarInteger varInteger;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IValue)varInteger, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       (IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81805()
{
    VarInteger varInteger;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, 0);
    IVariable[] iVariables = new IVariable[1];
    iVariables[0] = (IVariable)varInteger;
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IValue)varInteger, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       (IStatement[])null, iVariables);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81807()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    IVariable[] iVariables = new IVariable[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, iVariables);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81808()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IValue)varInteger, (IValue)varInteger, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       iStatements, (IVariable[])null);
    IStatement[] iStatements1 = new IStatement[1];
    IVariable[] iVariables = new IVariable[1];
    iStatements1[0] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements1, iVariables);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81809()
{
    VarInteger varInteger;
    VarInteger varInteger1;
    VarInteger varInteger2;
    StatementIncrementInteger statementIncrementInteger;
    VarInteger varInteger3;
    StatementIfOnCount statementIfOnCount;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    varInteger1 = VarIntegerFactory.Create(false, 0);
    varInteger2 = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    varInteger3 = VarIntegerFactory.Create(false, 0);
    IStatement[] iStatements = new IStatement[1];
    IVariable[] iVariables = new IVariable[2];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iVariables[0] = (IVariable)varInteger3;
    iVariables[1] = (IVariable)varInteger2;
    statementIfOnCount =
      StatementIfOnCountFactory.Create((IValue)varInteger, (IValue)varInteger1, 
                                       StatementIfOnCount.ComparisonOperator.GreaterThan, 
                                       iStatements, iVariables);
    IStatement[] iStatements1 = new IStatement[1];
    iStatements1[0] = (IStatement)statementIfOnCount;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements1, (IVariable[])null);
    this.TestAddSingleStatement((IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void TestAddSingleStatement81810()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    StatementInlineBlock statementInlineBlock1;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    IVariable[] iVariables = new IVariable[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, iVariables);
    IStatement[] iStatements1 = new IStatement[1];
    IVariable[] iVariables1 = new IVariable[1];
    iStatements1[0] = (IStatement)statementInlineBlock;
    statementInlineBlock1 =
      StatementInlineBlockFactory.Create(iStatements1, iVariables1);
    this.TestAddSingleStatement((IStatement)statementInlineBlock1);
}
    }
}
