using LINQToTTreeLib.Statements;
using System.Collections.Generic;
using System;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Tests.Statements
{
    public partial class StatementLoopOverGoodTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementLoopOverGoodTest))]
public void CodeItUp280()
{
    StatementInlineBlockTest.dummyVarName dummyVarName;
    StatementLoopOverGood statementLoopOverGood;
    IEnumerable<string> iEnumerable;
    dummyVarName =
      new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
    dummyVarName.InitialValue = (IValue)null;
    dummyVarName.Declare = false;
    dummyVarName.RawValue = (string)null;
    statementLoopOverGood = StatementLoopOverGoodFactory.Create
                                ((IValue)dummyVarName, (IValue)dummyVarName, 
                                 (IDeclaredParameter)dummyVarName, 
                                 (IStatement[])null, (IDeclaredParameter[])null);
    iEnumerable = this.CodeItUp(statementLoopOverGood);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementLoopOverGood);
    Assert.IsNotNull(((StatementInlineBlockBase)statementLoopOverGood).Statements);
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementLoopOverGood).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementLoopOverGood).Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementLoopOverGoodTest))]
public void CodeItUp28001()
{
    StatementInlineBlockTest.dummyVarName dummyVarName;
    StatementLoopOverGood statementLoopOverGood;
    IEnumerable<string> iEnumerable;
    dummyVarName =
      new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
    dummyVarName.InitialValue = (IValue)null;
    dummyVarName.Declare = false;
    dummyVarName.RawValue = (string)null;
    IDeclaredParameter[] iDeclaredParameters = new IDeclaredParameter[1];
    iDeclaredParameters[0] = (IDeclaredParameter)dummyVarName;
    statementLoopOverGood = StatementLoopOverGoodFactory.Create
                                ((IValue)dummyVarName, (IValue)dummyVarName, 
                                 (IDeclaredParameter)dummyVarName, (IStatement[])null, iDeclaredParameters);
    iEnumerable = this.CodeItUp(statementLoopOverGood);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementLoopOverGood);
    Assert.IsNotNull(((StatementInlineBlockBase)statementLoopOverGood).Statements);
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementLoopOverGood).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementLoopOverGood).Parent);
}
    }
}
