// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LINQToTTreeLib.Variables;
using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Tests
{
    public partial class StatementAssignTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void TryCombineStatementTest785()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)statementAssign);
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
    Assert.IsTrue(object.ReferenceEquals
                      (statementAssign.Expression, statementAssign.ResultVariable));
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException112()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void TryCombineStatementTest85401()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    StatementIncrementInteger statementIncrementInteger;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    b = this.TryCombineStatementTest
            (statementAssign, (IStatement)statementIncrementInteger);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
    Assert.IsTrue(object.ReferenceEquals
                      (statementAssign.Expression, statementAssign.ResultVariable));
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void TryCombineStatementTest85402()
{
    VarInteger varInteger;
    VarInteger varInteger1;
    StatementAssign statementAssign;
    StatementIncrementInteger statementIncrementInteger;
    bool b;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    varInteger1 = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger1);
    b = this.TryCombineStatementTest
            (statementAssign, (IStatement)statementIncrementInteger);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException629()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void TryCombineStatementTest727()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    VarInteger varInteger1;
    StatementAssign statementAssign1;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    varInteger1 = VarIntegerFactory.Create(false, 0);
    statementAssign1 =
      StatementAssignFactory.Create((IVariable)varInteger1, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)statementAssign1);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
    Assert.IsTrue(object.ReferenceEquals
                      (statementAssign.Expression, statementAssign.ResultVariable));
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
public void TryCombineStatementTest72701()
{
    VarInteger varInteger;
    VarInteger varInteger1;
    StatementAssign statementAssign;
    VarInteger varInteger2;
    StatementAssign statementAssign1;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    varInteger1 = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger1);
    varInteger2 = VarIntegerFactory.Create(false, 0);
    statementAssign1 =
      StatementAssignFactory.Create((IVariable)varInteger1, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)statementAssign1);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)statementAssign);
    Assert.IsNotNull(statementAssign.ResultVariable);
    Assert.IsNotNull(statementAssign.Expression);
}
    }
}
