// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LINQToTTreeLib.Statements;
using LINQToTTreeLib.Variables;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Tests.Statements
{
    public partial class StatementPairLoopTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementPairLoopTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void StatementPairLoopCtorThrowsArgumentNullException997()
{
    StatementPairLoop statementPairLoop;
    statementPairLoop =
      this.StatementPairLoopCtor((VarArray)null, (VarSimple)null, (VarSimple)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementPairLoopTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void StatementPairLoopCtorThrowsArgumentNullException158()
{
    VarArray varArray;
    StatementPairLoop statementPairLoop;
    varArray = VarArrayFactory.Create();
    statementPairLoop =
      this.StatementPairLoopCtor(varArray, (VarSimple)null, (VarSimple)null);
}
    }
}
