using LinqToTTreeInterfacesLib;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using LINQToTTreeLib.Variables;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Statements
{
    public partial class StatementInlineBlockTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet216()
{
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(statementInlineBlock.Statements);
    Assert.IsTrue(
                 object.ReferenceEquals(statementInlineBlock.Statements, (object)iEnumerable)
                 );
    Assert.IsNotNull(statementInlineBlock.DeclaredVariables);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet279()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(statementInlineBlock.Statements);
    Assert.IsTrue(
                 object.ReferenceEquals(statementInlineBlock.Statements, (object)iEnumerable)
                 );
    Assert.IsNotNull(statementInlineBlock.DeclaredVariables);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet27901()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(statementInlineBlock.Statements);
    Assert.IsTrue(
                 object.ReferenceEquals(statementInlineBlock.Statements, (object)iEnumerable)
                 );
    Assert.IsNotNull(statementInlineBlock.DeclaredVariables);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementInlineBlockTest))]
public void StatementsGet697()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    IEnumerable<IStatement> iEnumerable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[3];
    IVariable[] iVariables = new IVariable[3];
    iStatements[0] = (IStatement)statementIncrementInteger;
    iStatements[1] = (IStatement)statementIncrementInteger;
    iStatements[2] = (IStatement)statementIncrementInteger;
    statementInlineBlock =
      StatementInlineBlockFactory.Create(iStatements, iVariables);
    iEnumerable = this.StatementsGet(statementInlineBlock);
    Assert.IsNotNull((object)iEnumerable);
    Assert.IsNotNull((object)statementInlineBlock);
    Assert.IsNotNull(statementInlineBlock.Statements);
    Assert.IsTrue(
                 object.ReferenceEquals(statementInlineBlock.Statements, (object)iEnumerable)
                 );
    Assert.IsNotNull(statementInlineBlock.DeclaredVariables);
}
    }
}
