using LINQToTTreeLib.Variables;
using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Tests
{
    public partial class StatementAssignTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException475()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException71()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)statementAssign);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementAssignTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException125()
{
    VarInteger varInteger;
    StatementAssign statementAssign;
    bool b;
    varInteger = VarIntegerFactory.Create(false, -2);
    statementAssign =
      StatementAssignFactory.Create((IVariable)varInteger, (IValue)varInteger);
    b = this.TryCombineStatementTest(statementAssign, (IStatement)null);
}
    }
}
