// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Tests.Statements
{
    public partial class StatementLoopOverGroupItemsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementLoopOverGroupItemsTest))]
public void CodeItUpTest216()
{
    StatementInlineBlockTest.dummyVarName dummyVarName;
    StatementLoopOverGroupItems statementLoopOverGroupItems;
    string[] ss;
    dummyVarName =
      new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
    dummyVarName.InitialValue = (IValue)null;
    dummyVarName.Declare = false;
    dummyVarName.RawValue = (string)null;
    statementLoopOverGroupItems = StatementLoopOverGroupItemsFactory.Create
                                      ((IValue)dummyVarName, (IStatement)null);
    ss = this.CodeItUpTest(statementLoopOverGroupItems);
    Assert.IsNotNull((object)ss);
    Assert.AreEqual<int>(0, ss.Length);
    Assert.IsNotNull((object)statementLoopOverGroupItems);
    Assert.IsNotNull(statementLoopOverGroupItems.Counter);
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementLoopOverGroupItems).Statements);
    Assert.IsNotNull
        (((StatementInlineBlockBase)statementLoopOverGroupItems).DeclaredVariables);
    Assert.IsNull(((StatementInlineBlockBase)statementLoopOverGroupItems).Parent);
}
    }
}
