using LINQToTTreeLib.Variables;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Statements
{
    public partial class StatementIncrementIntegerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementIncrementIntegerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestTryCombineThrowsArgumentNullException542()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    b = this.TestTryCombine(statementIncrementInteger, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementIncrementIntegerTest))]
public void TestTryCombine335()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    b = this.TestTryCombine
            (statementIncrementInteger, (IStatement)statementIncrementInteger);
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)statementIncrementInteger);
    Assert.IsNotNull(statementIncrementInteger.Integer);
    Assert.AreEqual<string>("anint_1", statementIncrementInteger.Integer.RawValue);
    Assert.AreEqual<string>
        ("anint_1", statementIncrementInteger.Integer.VariableName);
    Assert.IsNotNull(statementIncrementInteger.Integer.InitialValue);
    Assert.AreEqual<bool>(false, statementIncrementInteger.Integer.Declare);
    Assert.IsNull(statementIncrementInteger.Parent);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementIncrementIntegerTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestTryCombineThrowsArgumentNullException62()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    b = this.TestTryCombine(statementIncrementInteger, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementIncrementIntegerTest))]
public void TestTryCombine943()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    VarInteger varInteger1;
    StatementIncrementInteger statementIncrementInteger1;
    bool b;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    varInteger1 = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger1 =
      StatementIncrementIntegerFactory.Create(varInteger1);
    b = this.TestTryCombine
            (statementIncrementInteger, (IStatement)statementIncrementInteger1);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)statementIncrementInteger);
    Assert.IsNotNull(statementIncrementInteger.Integer);
    Assert.AreEqual<string>("anint_1", statementIncrementInteger.Integer.RawValue);
    Assert.AreEqual<string>
        ("anint_1", statementIncrementInteger.Integer.VariableName);
    Assert.IsNotNull(statementIncrementInteger.Integer.InitialValue);
    Assert.AreEqual<bool>(false, statementIncrementInteger.Integer.Declare);
    Assert.IsNull(statementIncrementInteger.Parent);
}
    }
}
