using LINQToTTreeLib.Variables;
using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.Tests
{
    public partial class StatementRecordIndiciesTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StatementRecordIndiciesTest))]
[ExpectedException(typeof(ArgumentException))]
public void TryCombineStatementTestThrowsArgumentException30()
{
    VarInteger varInteger;
    StatementRecordIndicies statementRecordIndicies;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordIndicies = StatementRecordIndiciesFactory.Create
                                  ((IValue)varInteger, (IVariable)varInteger);
    b = this.TryCombineStatementTest(statementRecordIndicies, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementRecordIndiciesTest))]
[ExpectedException(typeof(ArgumentException))]
public void TryCombineStatementTestThrowsArgumentException200()
{
    VarInteger varInteger;
    StatementRecordIndicies statementRecordIndicies;
    bool b;
    varInteger = VarIntegerFactory.Create(false, -2);
    statementRecordIndicies = StatementRecordIndiciesFactory.Create
                                  ((IValue)varInteger, (IVariable)varInteger);
    b = this.TryCombineStatementTest(statementRecordIndicies, (IStatement)null);
}
[TestMethod]
[PexGeneratedBy(typeof(StatementRecordIndiciesTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TryCombineStatementTestThrowsArgumentNullException323()
{
    VarInteger varInteger;
    StatementRecordIndicies statementRecordIndicies;
    bool b;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordIndicies = StatementRecordIndiciesFactory.Create
                                  ((IValue)varInteger, (IVariable)varInteger);
    b = this.TryCombineStatementTest
            (statementRecordIndicies, (IStatement)statementRecordIndicies);
}
    }
}
