// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LINQToTTreeLib.Statements;
using LINQToTTreeLib.Tests.Factories;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Tests
{
    public partial class TestStatementRecordValue
    {
[TestMethod]
[PexGeneratedBy(typeof(TestStatementRecordValue))]
public void TestTryCombineStatement189()
{
    StatementInlineBlockTest.dummyVarName dummyVarName;
    StatementRecordValue statementRecordValue;
    StatementRecordValue statementRecordValue1;
    CodeOptimizerTest codeOptimizerTest;
    bool b;
    dummyVarName =
      new StatementInlineBlockTest.dummyVarName((string)null, (Type)null);
    dummyVarName.InitialValue = (IValue)null;
    dummyVarName.Declare = false;
    dummyVarName.RawValue = (string)null;
    statementRecordValue = StatementRecordValueFactory.Create
                               ((IDeclaredParameter)dummyVarName, (IValue)dummyVarName, 
                                (IDeclaredParameter)dummyVarName, false);
    statementRecordValue1 = StatementRecordValueFactory.Create
                                ((IDeclaredParameter)dummyVarName, (IValue)dummyVarName, 
                                 (IDeclaredParameter)dummyVarName, false);
    codeOptimizerTest = CodeOptimizerTestFactory.Create(false);
    b = this.TestTryCombineStatement
            (statementRecordValue1, (IStatement)statementRecordValue, 
                                    (ICodeOptimizationService)codeOptimizerTest);
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)statementRecordValue1);
    Assert.IsNull(statementRecordValue1.Parent);
}
    }
}
