// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LINQToTTreeLib.Statements;
using LINQToTTreeLib.Variables;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Tests
{
    public partial class TestStatemenRecordValue
    {
[TestMethod]
[PexGeneratedBy(typeof(TestStatemenRecordValue))]
[PexRaisedException(typeof(ArgumentNullException))]
public void TestRenameVariableThrowsArgumentNullException900()
{
    VarInteger varInteger;
    StatementRecordValue statementRecordValue;
    StatementRecordValue statementRecordValue1;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordValue = StatementRecordValueFactory.Create
                               ((IVariable)varInteger, (IValue)varInteger, (IVariable)varInteger, false);
    statementRecordValue1 =
      this.TestRenameVariable(statementRecordValue, (string)null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TestStatemenRecordValue))]
[PexRaisedException(typeof(ArgumentNullException))]
public void TestRenameVariableThrowsArgumentNullException302()
{
    VarInteger varInteger;
    StatementRecordValue statementRecordValue;
    StatementRecordValue statementRecordValue1;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordValue = StatementRecordValueFactory.Create
                               ((IVariable)varInteger, (IValue)varInteger, (IVariable)varInteger, false);
    statementRecordValue1 =
      this.TestRenameVariable(statementRecordValue, "", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TestStatemenRecordValue))]
[PexRaisedException(typeof(ArgumentNullException))]
public void TestRenameVariableThrowsArgumentNullException355()
{
    VarInteger varInteger;
    StatementRecordValue statementRecordValue;
    StatementRecordValue statementRecordValue1;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordValue = StatementRecordValueFactory.Create
                               ((IVariable)varInteger, (IValue)varInteger, (IVariable)varInteger, false);
    statementRecordValue1 =
      this.TestRenameVariable(statementRecordValue, "anin", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TestStatemenRecordValue))]
[PexRaisedException(typeof(ArgumentNullException))]
public void TestRenameVariableThrowsArgumentNullException178()
{
    VarInteger varInteger;
    StatementRecordValue statementRecordValue;
    StatementRecordValue statementRecordValue1;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementRecordValue = StatementRecordValueFactory.Create
                               ((IVariable)varInteger, (IValue)varInteger, (IVariable)varInteger, false);
    statementRecordValue1 =
      this.TestRenameVariable(statementRecordValue, "\u0100\0\0\0", (string)null);
}
    }
}
