using System;
using System.Collections.Generic;
using LinqToTTreeInterfacesLib;
using LinqToTTreeInterfacesLib.Moles;
using LINQToTTreeLib.Statements;
using LINQToTTreeLib.Variables.Moles;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Moles;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using LINQToTTreeLib.Moles;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class CombinedGeneratedCodeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException817()
{
    CombinedGeneratedCode combinedGeneratedCode;
    combinedGeneratedCode =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException893()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException510()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    ss[0] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException838()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    ss[0] = "\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException787()
{
    CombinedGeneratedCode combinedGeneratedCode;
    SCombinedGeneratedCode sCombinedGeneratedCode;
    combinedGeneratedCode =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    sCombinedGeneratedCode = new SCombinedGeneratedCode();
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)sCombinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException535()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    string[] ss1 = new string[2];
    ss[0] = "";
    ss1[1] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, ss1, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException431()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    string[] ss1 = new string[6];
    ss[0] = "\0\0\0\0";
    ss1[0] = "\0\0\0\0\0\0";
    ss1[1] = "\0\0\0";
    ss1[2] = "\0\0";
    ss1[3] = "";
    ss1[4] = "\0";
    ss1[5] = "\0\0\0\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, ss1, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException990()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[6];
    ss[0] = "";
    ss1[0] = "";
    ss1[1] = "\0\0\0\0\0";
    ss1[2] = "\0\0";
    ss1[3] = "\0\0\0";
    ss1[4] = "\0\0\0\0\0\0";
    ss1[5] = "\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, ss1, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException805()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[2];
    ss[0] = "\0\0";
    ss[1] = "\0\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
    }
}
