using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class CombinedGeneratedCodeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException161()
{
    CombinedGeneratedCode combinedGeneratedCode;
    combinedGeneratedCode =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException779()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException371()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    ss[0] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException858()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[1];
    ss[0] = "\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException732()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    combinedGeneratedCode =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException552()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[2];
    ss[0] = "\u0100";
    ss[1] = "\u0100";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException461()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException400()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[2];
    ss[0] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException872()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[1];
    ss[0] = "\u0089";
    ss1[0] = "\u0089";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, ss1, (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException388()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[1];
    ss[0] = "\u0100";
    ss1[0] = "\u0100";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, ss1, (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException580()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[3];
    ss[0] = "\u0089";
    ss1[0] = "\u0089";
    ss1[1] = "\u008b";
    ss1[2] = "\u008b";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, ss1, (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException14()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[2];
    ss[0] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException263()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[2];
    ss[0] = "\u0100";
    ss[1] = "\u0102";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException697()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[2];
    ss[0] = "";
    ss1[0] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, ss1, (IBookingStatementBlock[])null);
    string[] ss2 = new string[1];
    combinedGeneratedCode1 = CombinedGeneratedCodeFactory.Create
                                 ((string[])null, (string[])null, ss2, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException687()
{
    CombinedGeneratedCode combinedGeneratedCode;
    string[] ss = new string[5];
    ss[0] = "\u0400";
    ss[1] = "\0\0";
    ss[2] = "\u0400\0\0";
    ss[4] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException677()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[5];
    ss[1] = "\0";
    ss[2] = "\0\0\0";
    ss[3] = "\0\0";
    ss[4] = "\0\0\0\0";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, (string[])null, ss, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException942()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[1];
    string[] ss1 = new string[2];
    ss[0] = "";
    ss1[0] = "\0";
    ss1[1] = "";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                (ss, (string[])null, ss1, (IBookingStatementBlock[])null);
    string[] ss2 = new string[1];
    combinedGeneratedCode1 = CombinedGeneratedCodeFactory.Create
                                 ((string[])null, (string[])null, ss2, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(CombinedGeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddGeneratedCodeThrowsArgumentException37001()
{
    CombinedGeneratedCode combinedGeneratedCode;
    CombinedGeneratedCode combinedGeneratedCode1;
    string[] ss = new string[3];
    ss[0] = "\u0900";
    ss[1] = "\u0140";
    ss[2] = "\u0100";
    combinedGeneratedCode = CombinedGeneratedCodeFactory.Create
                                ((string[])null, ss, (string[])null, (IBookingStatementBlock[])null);
    combinedGeneratedCode1 =
      CombinedGeneratedCodeFactory.Create((string[])null, (string[])null, 
                                          (string[])null, (IBookingStatementBlock[])null);
    this.AddGeneratedCode
        (combinedGeneratedCode1, (IExecutableCode)combinedGeneratedCode);
}
    }
}
