// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib
{
    public partial class FutureValueTTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FutureValueTTest))]
[ExpectedException(typeof(ArgumentException))]
public void Constructor01ThrowsArgumentException202()
{
    FutureValue<int> futureValue;
    futureValue = this.Constructor01<int>((TTreeQueryExecutor)null);
}
[TestMethod]
[PexGeneratedBy(typeof(FutureValueTTest))]
public void Constructor227()
{
    FutureValue<int> futureValue;
    futureValue = this.Constructor<int>(0);
    Assert.IsNotNull((object)futureValue);
}
    }
}
