using LINQToTTreeLib.Variables;
using LINQToTTreeLib.Statements;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class GeneratedCodeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestChangeScopeThrowsArgumentNullException782()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
public void TestChangeScope261()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[0];
    this.TestChangeScope(iStatements, 
                         (IStatement)statementInlineBlock, (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestChangeScopeThrowsArgumentNullException8()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[2];
    iStatements[0] = (IStatement)statementIncrementInteger;
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
public void TestChangeScope659()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    StatementInlineBlock statementInlineBlock1;
    StatementInlineBlock statementInlineBlock2;
    StatementInlineBlock statementInlineBlock3;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementInlineBlock;
    statementInlineBlock1 =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    IStatement[] iStatements1 = new IStatement[1];
    iStatements1[0] = (IStatement)statementInlineBlock1;
    statementInlineBlock2 =
      StatementInlineBlockFactory.Create(iStatements1, (IVariable[])null);
    statementInlineBlock3 =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements2 = new IStatement[1];
    iStatements2[0] = (IStatement)statementInlineBlock2;
    this.TestChangeScope(iStatements2, 
                         (IStatement)statementIncrementInteger, (IStatement)statementInlineBlock3);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException656()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, 0);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[0];
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException530()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, 1);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[0];
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException495()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException870()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementInlineBlock;
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException367()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    StatementInlineBlock statementInlineBlock1;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementInlineBlock;
    statementInlineBlock1 =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    IStatement[] iStatements1 = new IStatement[1];
    iStatements1[0] = (IStatement)statementInlineBlock1;
    this.TestChangeScope(iStatements1, 
                         (IStatement)statementIncrementInteger, (IStatement)statementInlineBlock);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentException))]
public void TestChangeScopeThrowsArgumentException77()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementInlineBlock statementInlineBlock;
    StatementInlineBlock statementInlineBlock1;
    StatementInlineBlock statementInlineBlock2;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementInlineBlock =
      StatementInlineBlockFactory.Create((IStatement[])null, (IVariable[])null);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementInlineBlock;
    statementInlineBlock1 =
      StatementInlineBlockFactory.Create(iStatements, (IVariable[])null);
    IStatement[] iStatements1 = new IStatement[1];
    iStatements1[0] = (IStatement)statementInlineBlock1;
    statementInlineBlock2 =
      StatementInlineBlockFactory.Create(iStatements1, (IVariable[])null);
    IStatement[] iStatements2 = new IStatement[2];
    iStatements2[0] = (IStatement)statementInlineBlock2;
    iStatements2[1] = (IStatement)statementIncrementInteger;
    this.TestChangeScope(iStatements2, (IStatement)statementIncrementInteger, 
                                       (IStatement)statementIncrementInteger);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
public void TestChangeScope26103()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    StatementIncrementInteger statementIncrementInteger1;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    statementIncrementInteger1 = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[0];
    this.TestChangeScope(iStatements, (IStatement)statementIncrementInteger, 
                                      (IStatement)statementIncrementInteger1);
}
    }
}
