// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using LINQToTTreeLib.Variables;

namespace LINQToTTreeLib
{
    public partial class GeneratedCodeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
public void TestAddTransfer218()
{
    GeneratedCode generatedCode;
    generatedCode = GeneratedCodeFactory.Create();
    VarInteger s0 = new VarInteger();
    this.TestAddTransfer(generatedCode, (IVariable)s0);
    Assert.IsNotNull((object)generatedCode);
    Assert.IsNull(generatedCode.ResultValue);
    Assert.IsNotNull(generatedCode.CodeBody);
    Assert.IsNotNull(generatedCode.VariablesToTransfer);
}
[TestMethod]
[PexGeneratedBy(typeof(GeneratedCodeTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestAddTransferThrowsArgumentNullException404()
{
    GeneratedCode generatedCode;
    generatedCode = GeneratedCodeFactory.Create();
    this.TestAddTransfer(generatedCode, (IVariable)null);
}
    }
}
