using System;
using System.IO;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="TTreeQueryExecutorTest.Constructor.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class TTreeQueryExecutorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException253()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException232()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, "");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException810()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException531()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, "\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException93()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, "\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException139()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor =
      this.Constructor((FileInfo)null, (string)null, (string[])null, "\u0100\u0100");
}
    }
}
