using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.IO;
// <copyright file="TTreeQueryExecutorTest.Constructor.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class TTreeQueryExecutorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
public void Constructor298()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 0, "\0");
    Assert.IsNotNull((object)tTreeQueryExecutor);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
public void Constructor796()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 2, "\0");
    Assert.IsNotNull((object)tTreeQueryExecutor);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException597()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 0, "");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException252()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException396()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 2, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException634()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException606()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 1, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
public void Constructor266()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 3, "\0");
    Assert.IsNotNull((object)tTreeQueryExecutor);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException655()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(1, 2, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(FileNotFoundException))]
public void ConstructorThrowsFileNotFoundException280()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 1, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException876()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(3, 2, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException92()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 3, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException637()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, "\u0100");
}
    }
}
