using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.IO;
// <copyright file="TTreeQueryExecutorTest.Constructor.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class TTreeQueryExecutorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException29()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 0, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException761()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 0, 1, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException793()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(1, 0, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException764()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 1, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException306()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException337()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, "");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException484()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException939()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 0, 0, "\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException779()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 0, 2, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException144()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 0, 3, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException493()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(3, 0, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException51()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 2, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException531()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(0, 3, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException415()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(1, 2, 2, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException76()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 1, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(FileNotFoundException))]
public void ConstructorThrowsFileNotFoundException839()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 1, 0, "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
[ExpectedException(typeof(FileNotFoundException))]
public void ConstructorThrowsFileNotFoundException633()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 1, 1, "\u0100\u0100");
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
public void Constructor298()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 0, "\0");
    Assert.IsNotNull((object)tTreeQueryExecutor);
}
[TestMethod]
[PexGeneratedBy(typeof(TTreeQueryExecutorTest))]
public void Constructor796()
{
    TTreeQueryExecutor tTreeQueryExecutor;
    tTreeQueryExecutor = this.Constructor(2, 2, 2, "\0");
    Assert.IsNotNull((object)tTreeQueryExecutor);
}
    }
}
