using System.Collections.Generic;

namespace TTreeDataModel
{
    /// <summary>
    /// Represents a root class that isn't built into ROOT.
    /// </summary>
    public class ROOTClassShell
    {
        List<IClassItem> _items = new List<IClassItem>();
        public ROOTClassShell(string name)
        {
            // TODO: Complete member initialization
            this.Name = name;
        }

        /// <summary>
        /// To allow for serialization
        /// </summary>
        public ROOTClassShell()
        {
        }

        /// <summary>
        /// Get the name of the class we represent
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Return all the items in this class
        /// </summary>
        public List<IClassItem> Items { get { return _items; } }

        /// <summary>
        /// Add an item to this class.
        /// </summary>
        /// <param name="item"></param>
        public void Add(IClassItem item)
        {
            _items.Add(item);
        }

        public string SubClassName { get; set; }

        /// <summary>
        /// Get or set the path to a proxy file generated by root. Used when this
        /// guy represents an actual class.
        /// </summary>
        public string NtupleProxyPath { get; set; }
    }
}
