// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.Variables
{
    public partial class VarUtilsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(VarUtilsTest))]
public void CastToType505()
{
    string s;
    s = this.CastToType(0, 0);
    Assert.AreEqual<string>("((int)10)", s);
}
[TestMethod]
[PexGeneratedBy(typeof(VarUtilsTest))]
public void CastToType459()
{
    string s;
    s = this.CastToType(0, 1);
    Assert.AreEqual<string>("((double)((int)10))", s);
}
[TestMethod]
[PexGeneratedBy(typeof(VarUtilsTest))]
public void CastToType48()
{
    string s;
    s = this.CastToType(1, 0);
    Assert.AreEqual<string>("((int)((double)10.0))", s);
}
[TestMethod]
[PexGeneratedBy(typeof(VarUtilsTest))]
public void CastToType184()
{
    string s;
    s = this.CastToType(2, 0);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(VarUtilsTest))]
public void CastToType906()
{
    string s;
    s = this.CastToType(0, 2);
    Assert.AreEqual<string>("", s);
}
    }
}
