using LinqToTTreeInterfacesLib;
using LINQToTTreeLib.ResultOperators;
using Remotion.Linq.Clauses.ResultOperators;
using Remotion.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
using LINQToTTreeLib.Variables;
using LINQToTTreeLib.Statements;
using ROOTNET;
// <copyright file="ROCountTest.ProcessResultOperator.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class ROCountTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException146()
{
    IVariable iVariable;
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, (GeneratedCode)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException315()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, 0);
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
public void ProcessResultOperator44()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, 0);
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    CountResultOperator s1 = new CountResultOperator();
    iVariable = this.ProcessResultOperator(s0, s1, (QueryModel)null, generatedCode);
    Assert.IsNotNull((object)iVariable);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException898()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, 1);
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException261()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    string[] ss = new string[1];
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  (string[])null, (NTObject[])null, ss);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException692()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    string[] ss = new string[1];
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException53()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    string[] ss = new string[1];
    ss[0] = "";
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException292()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      VarInteger varInteger;
      NTObject nTObject;
      GeneratedCode generatedCode;
      IVariable iVariable;
      varInteger = VarIntegerFactory.Create(false, 0);
      nTObject = NTObjectFactory.Create();
      disposables.Add((IDisposable)nTObject);
      NTObject[] nTObjects = new NTObject[1];
      nTObjects[0] = nTObject;
      generatedCode =
        GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                    (string[])null, nTObjects, (string[])null);
      ROCount s0 = new ROCount();
      iVariable = this.ProcessResultOperator
                      (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException202()
{
    VarInteger varInteger;
    StatementIncrementInteger statementIncrementInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
    IStatement[] iStatements = new IStatement[1];
    iStatements[0] = (IStatement)statementIncrementInteger;
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger, iStatements, 
                                                (string[])null, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException270()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = VarIntegerFactory.Create(false, int.MaxValue);
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    generatedCode =
      GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                  ss, (NTObject[])null, (string[])null);
    ROCount s0 = new ROCount();
    iVariable = this.ProcessResultOperator
                    (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(ROCountTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException371()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      VarInteger varInteger;
      NTObject nTObject;
      GeneratedCode generatedCode;
      IVariable iVariable;
      varInteger = VarIntegerFactory.Create(false, int.MaxValue);
      nTObject = NTObjectFactory.Create();
      disposables.Add((IDisposable)nTObject);
      string[] ss = new string[2];
      NTObject[] nTObjects = new NTObject[2];
      ss[0] = "";
      ss[1] = "";
      nTObjects[0] = nTObject;
      nTObjects[1] = nTObject;
      generatedCode =
        GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null, 
                                    ss, nTObjects, (string[])null);
      ROCount s0 = new ROCount();
      iVariable = this.ProcessResultOperator
                      (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
      disposables.Dispose();
    }
}
    }
}
