using System;
using System.Linq.Expressions;
using LinqToTTreeInterfacesLib;
using LINQToTTreeLib.ResultOperators;
using LINQToTTreeLib.Statements;
using LINQToTTreeLib.Variables;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Remotion.Linq;
using Remotion.Linq.Clauses.ResultOperators;
using ROOTNET;
// <copyright file="ROCountTest.ProcessResultOperator.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib
{
    public partial class ROCountTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException26()
        {
            Expression expression;
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, (GeneratedCode)null);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException535()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 0);
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          (string[])null, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(InvalidOperationException))]
        public void ProcessResultOperatorThrowsTypeInitializationException996()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 0);
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          (string[])null, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            CountResultOperator s1 = new CountResultOperator();
            expression = this.ProcessResultOperator(s0, s1, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException707()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 0);
            string[] ss = new string[1];
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          ss, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException624()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 0);
            string[] ss = new string[1];
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          (string[])null, (NTObject[])null, ss);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException887()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 1);
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          (string[])null, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException772()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, 0);
            string[] ss = new string[1];
            ss[0] = "";
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          ss, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException708()
        {
            VarInteger varInteger;
            StatementIncrementInteger statementIncrementInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, int.MaxValue);
            statementIncrementInteger = StatementIncrementIntegerFactory.Create(varInteger);
            IStatement[] iStatements = new IStatement[1];
            iStatements[0] = (IStatement)statementIncrementInteger;
            generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger, iStatements,
                                                        (string[])null, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException466()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                VarInteger varInteger;
                NTObject nTObject;
                GeneratedCode generatedCode;
                Expression expression;
                varInteger = VarIntegerFactory.Create(false, 0);
                nTObject = NTObjectFactory.Create();
                disposables.Add((IDisposable)nTObject);
                NTObject[] nTObjects = new NTObject[1];
                nTObjects[0] = nTObject;
                generatedCode =
                  GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                              (string[])null, nTObjects, (string[])null);
                ROCount s0 = new ROCount();
                expression = this.ProcessResultOperator
                                 (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
                disposables.Dispose();
            }
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException723()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, int.MaxValue);
            string[] ss = new string[2];
            ss[0] = "";
            ss[1] = "";
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          ss, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            expression = this.ProcessResultOperator
                             (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(InvalidOperationException))]
        public void ProcessResultOperatorThrowsInvalidOperationException660()
        {
            VarInteger varInteger;
            GeneratedCode generatedCode;
            Expression expression;
            varInteger = VarIntegerFactory.Create(false, int.MaxValue);
            generatedCode =
              GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                          (string[])null, (NTObject[])null, (string[])null);
            ROCount s0 = new ROCount();
            CountResultOperator s1 = new CountResultOperator();
            expression = this.ProcessResultOperator(s0, s1, (QueryModel)null, generatedCode);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(ROCountTest))]
        [ExpectedException(typeof(ArgumentNullException))]
        public void ProcessResultOperatorThrowsArgumentNullException106()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                VarInteger varInteger;
                NTObject nTObject;
                GeneratedCode generatedCode;
                Expression expression;
                varInteger = VarIntegerFactory.Create(false, int.MaxValue);
                nTObject = NTObjectFactory.Create();
                disposables.Add((IDisposable)nTObject);
                string[] ss = new string[2];
                NTObject[] nTObjects = new NTObject[2];
                ss[0] = "";
                ss[1] = "";
                nTObjects[0] = nTObject;
                nTObjects[1] = nTObject;
                generatedCode =
                  GeneratedCodeFactory.Create((IVariable)varInteger, (IStatement[])null,
                                              ss, nTObjects, (string[])null);
                ROCount s0 = new ROCount();
                expression = this.ProcessResultOperator
                                 (s0, (CountResultOperator)null, (QueryModel)null, generatedCode);
                disposables.Dispose();
            }
        }
    }
}
