// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Remotion.Data.Linq;
using Remotion.Data.Linq.Clauses;
using Remotion.Data.Linq.Clauses.ResultOperators;
using LINQToTTreeLib.Variables;
using LINQToTTreeLib;

namespace LINQToTTreeLib.ResultOperators
{
    public partial class TakeSkipOperatorsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException251()
{
    IVariable iVariable;
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable = this.ProcessResultOperator
                    (s0, (ResultOperatorBase)null, (QueryModel)null, (IGeneratedCode)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException782()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable = this.ProcessResultOperator(s0, (ResultOperatorBase)null, 
                                           (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void ProcessResultOperatorThrowsAssertFailedException859()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    takeResultOperator = TakeResultOperatorFactory.Create(0);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void ProcessResultOperatorThrowsAssertFailedException412()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    takeResultOperator = TakeResultOperatorFactory.Create(int.MaxValue);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void ProcessResultOperatorThrowsAssertFailedException973()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    takeResultOperator = TakeResultOperatorFactory.Create(1);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void ProcessResultOperatorThrowsAssertFailedException467()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    takeResultOperator = TakeResultOperatorFactory.Create(int.MinValue);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void ProcessResultOperatorThrowsAssertFailedException561()
{
    VarInteger varInteger;
    GeneratedCode generatedCode;
    SkipResultOperator skipResultOperator;
    IVariable iVariable;
    varInteger = new VarInteger();
    generatedCode = GeneratedCodeFactory.Create((IVariable)varInteger);
    skipResultOperator = SkipResultOperatorFactory.Create(0);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)skipResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)generatedCode);
}
    }
}
