// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Remotion.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace LINQToTTreeLib.QueryVisitors
{
    public partial class FormattingQueryVisitorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FormattingQueryVisitorTest))]
public void Format462()
{
    string s;
    s = this.Format((QueryModel)null);
    Assert.AreEqual<string>("QueryModel(null)", s);
}
    }
}
