// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using LINQToTTreeLib.Variables;

namespace LINQToTTreeLib
{
    public partial class CodeContextTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CodeContextTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void AddThrowsArgumentNullException979()
{
    CodeContext codeContext;
    codeContext = new CodeContext();
    this.Add(codeContext, (string)null, (IValue)null);
}
[TestMethod]
[PexGeneratedBy(typeof(CodeContextTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void AddThrowsArgumentNullException545()
{
    CodeContext codeContext;
    codeContext = new CodeContext();
    this.Add(codeContext, "", (IValue)null);
}
[TestMethod]
[PexGeneratedBy(typeof(CodeContextTest))]
[ExpectedException(typeof(ArgumentException))]
public void AddThrowsArgumentException561()
{
    CodeContext codeContext;
    codeContext = new CodeContext();
    VarInteger s0 = new VarInteger();
    this.Add(codeContext, "", (IValue)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(CodeContextTest))]
public void Add748()
{
    CodeContext codeContext;
    codeContext = new CodeContext();
    VarInteger s0 = new VarInteger();
    this.Add(codeContext, "\0", (IValue)s0);
    Assert.IsNotNull((object)codeContext);
}
    }
}
