using System.Linq.Expressions;
using LinqToTTreeInterfacesLib;
using System.ComponentModel.Composition.Hosting;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace LINQToTTreeLib.TypeHandlers.CPPCode
{
    public partial class TypeHandlerCPPCodeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TypeHandlerCPPCodeTest))]
public void ProcessMethodCall170()
{
    TypeHandlerCPPCode typeHandlerCPPCode;
    Expression expression;
    typeHandlerCPPCode = new TypeHandlerCPPCode();
    expression =
      this.ProcessMethodCall(typeHandlerCPPCode, (MethodCallExpression)null, 
                             (IGeneratedQueryCode)null, (ICodeContext)null, (CompositionContainer)null);
    Assert.IsNull((object)expression);
    Assert.IsNotNull((object)typeHandlerCPPCode);
}
    }
}
