// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace LINQToTTreeLib.Tests
{
    public partial class ExpressionUtilitiesTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestApplyThrowsArgumentNullException975()
{
    string s;
    s = this.TestApply((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void TestApplyThrowsArgumentNullException739()
{
    string s;
    s = this.TestApply("");
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply40()
{
    string s;
    s = this.TestApply("\0");
    Assert.AreEqual<string>("(\0)", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply370()
{
    string s;
    s = this.TestApply("(");
    Assert.AreEqual<string>("(", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply981()
{
    string s;
    s = this.TestApply("\u00e9");
    Assert.AreEqual<string>("\u00e9", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply270()
{
    string s;
    s = this.TestApply("(\0");
    Assert.AreEqual<string>("(\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply454()
{
    string s;
    s = this.TestApply("()");
    Assert.AreEqual<string>("()", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply662()
{
    string s;
    s = this.TestApply("((");
    Assert.AreEqual<string>("((", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply464()
{
    string s;
    s = this.TestApply("s\u0089");
    Assert.AreEqual<string>("(s\u0089)", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply953()
{
    string s;
    s = this.TestApply("\u00e0\u00e5");
    Assert.AreEqual<string>("\u00e0\u00e5", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply516()
{
    string s;
    s = this.TestApply("(\0\0\0");
    Assert.AreEqual<string>("(\0\0\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply355()
{
    string s;
    s = this.TestApply("()\0\0");
    Assert.AreEqual<string>("(()\0\0)", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply235()
{
    string s;
    s = this.TestApply("(((\0");
    Assert.AreEqual<string>("(((\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply511()
{
    string s;
    s = this.TestApply("\u0100\u0100\0\0");
    Assert.AreEqual<string>("(\u0100\u0100\0\0)", s);
}
[TestMethod]
[PexGeneratedBy(typeof(ExpressionUtilitiesTest))]
public void TestApply555()
{
    string s;
    s = this.TestApply("(())");
    Assert.AreEqual<string>("(())", s);
}
    }
}
