// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using LinqToTTreeInterfacesLib;
using Remotion.Data.Linq.Clauses;
using Remotion.Data.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using LINQToTTreeLib.Moles;
using LINQToTTreeLib;
using Remotion.Data.Linq.Clauses.ResultOperators;

namespace LINQToTTreeLib.ResultOperators
{
    public partial class TakeSkipOperatorsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException379()
{
    IVariable iVariable;
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable = this.ProcessResultOperator
                    (s0, (ResultOperatorBase)null, (QueryModel)null, (IGeneratedCode)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException951()
{
    SGeneratedCode sGeneratedCode;
    IVariable iVariable;
    sGeneratedCode = new SGeneratedCode();
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable = this.ProcessResultOperator(s0, (ResultOperatorBase)null, 
                                           (QueryModel)null, (IGeneratedCode)sGeneratedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void ProcessResultOperatorThrowsArgumentNullException2()
{
    GeneratedCode generatedCode;
    IVariable iVariable;
    generatedCode = GeneratedCodeFactory.Create();
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable = this.ProcessResultOperator(s0, (ResultOperatorBase)null, 
                                           (QueryModel)null, (IGeneratedCode)generatedCode);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
public void ProcessResultOperator990()
{
    SGeneratedCode sGeneratedCode;
    SkipResultOperator skipResultOperator;
    IVariable iVariable;
    sGeneratedCode = new SGeneratedCode();
    skipResultOperator = SkipResultOperatorFactory.Create(0);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)skipResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)sGeneratedCode);
    Assert.IsNull((object)iVariable);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
public void ProcessResultOperator539()
{
    SGeneratedCode sGeneratedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    sGeneratedCode = new SGeneratedCode();
    takeResultOperator = TakeResultOperatorFactory.Create(0);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)sGeneratedCode);
    Assert.IsNull((object)iVariable);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(TakeSkipOperatorsTest))]
public void ProcessResultOperator53902()
{
    SGeneratedCode sGeneratedCode;
    TakeResultOperator takeResultOperator;
    IVariable iVariable;
    sGeneratedCode = new SGeneratedCode();
    takeResultOperator = TakeResultOperatorFactory.Create(1);
    ROTakeSkipOperators s0 = new ROTakeSkipOperators();
    iVariable =
      this.ProcessResultOperator(s0, (ResultOperatorBase)takeResultOperator, 
                                 (QueryModel)null, (IGeneratedCode)sGeneratedCode);
    Assert.IsNull((object)iVariable);
    Assert.IsNotNull((object)s0);
}
    }
}
