using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System;
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace TTreeClassGenerator
{
    public partial class ClassGeneratorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ClassGeneratorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GenerateClasssThrowsArgumentNullException966()
{
    ClassGenerator s0 = new ClassGenerator();
    this.GenerateClasss(s0, 0, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ClassGeneratorTest))]
[ExpectedException(typeof(ArgumentException))]
public void GenerateClasssThrowsArgumentException382()
{
    ClassGenerator s0 = new ClassGenerator();
    this.GenerateClasss(s0, 1, 0, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ClassGeneratorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GenerateClasssThrowsArgumentNullException172()
{
    ClassGenerator s0 = new ClassGenerator();
    this.GenerateClasss(s0, 0, 1, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(ClassGeneratorTest))]
[ExpectedException(typeof(ArgumentException))]
public void GenerateClasssThrowsArgumentException981()
{
    ClassGenerator s0 = new ClassGenerator();
    this.GenerateClasss(s0, 1, 1, (string)null);
}
    }
}
